<a href="https://colab.research.google.com/github/APARNA989/coding/blob/main/Image_Classification.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

# New section

In [1]:

# Data : Images
# 1. Download manually the images from Google
# 2. Download dataset from kaggle.com
# 3. Build a Image Web Crawler
# 4. Use python librares to scrape the images (Using)

In [2]:
!pip install bing-image-downloader

In [3]:
!mkdir images

In [4]:
from bing_image_downloader import downloader
downloader.download("pretty sunflower",limit=30,output_dir='images',
                    adult_filter_off=True)




[!!]Indexing page: 1

[%] Indexed 13 Images on Page 1.


[%] Downloading Image #1 from https://emmalovesweddings.com/wp-content/uploads/2019/08/sunflower-wedding-cake-ideas.jpg
[%] File Downloaded !

[%] Downloading Image #2 from https://emmalovesweddings.com/wp-content/uploads/2019/07/simple-protea-wedding-bouquet.jpg
[%] File Downloaded !

[%] Downloading Image #3 from https://i.pinimg.com/736x/dd/20/0c/dd200cd836acc855dd1d51c709c2a50b--giant-sunflower-sunflower-flower.jpg
[%] File Downloaded !

[%] Downloading Image #4 from https://bestanimations.com/Nature/Flora/beautiful-flower-animated-gif5.gif
[%] File Downloaded !

[%] Downloading Image #5 from https://www.bing.com/th/id/OGC.e05f040180d53eea684e8bd417ae1906?pid=1.7&amp;rurl=https%3a%2f%2fbestanimations.com%2fNature%2fFlora%2fbeautiful-flower-animated-gif5.gif&amp;ehk=FWMOrkEwVVqVQndXaUXsKJz2LhLVP4p9ZdPMfcYbDfA%3d
[!] Issue getting: https://www.bing.com/th/id/OGC.e05f040180d53eea684e8bd417ae1906?pid=1.7&amp;rurl=https%3a%2f%2f

In [5]:
from bing_image_downloader import downloader 
downloader.download("rugby ball leather",limit=30,output_dir='images',
                    adult_filter_off=True)



[!!]Indexing page: 1

[%] Indexed 12 Images on Page 1.


[%] Downloading Image #1 from https://cdn1.bigcommerce.com/server1000/4dd02/products/682/images/3492/_MG_0374v2__78298.1332357807.455.455.jpg?c=2
[%] File Downloaded !

[%] Downloading Image #2 from https://cdn.notonthehighstreet.com/fs/6d/b6/5cda-1aa6-492c-b641-ff1185634649/original_leather-rugby-shaped-washbag.jpg
[%] File Downloaded !

[%] Downloading Image #3 from https://cdn.notonthehighstreet.com/fs/14/cb/45f8-4377-4358-9cc0-36c127d448d0/original_personalised-vintage-leather-rugby-ball.jpg
[%] File Downloaded !

[%] Downloading Image #4 from https://static.vecteezy.com/system/resources/previews/000/104/104/original/vector-football-texture-and-lace.jpg
[%] File Downloaded !

[%] Downloading Image #5 from https://d2gg9evh47fn9z.cloudfront.net/800px_COLOURBOX19173696.jpg
[%] File Downloaded !

[%] Downloading Image #6 from https://www.rasasports.com/antiquefootball/image017.jpg
[Error]Invalid image, not saving https://www.ra

In [6]:
from bing_image_downloader import downloader
downloader.download("icecream cone",limit=30,output_dir='images',
                    adult_filter_off=True)



[!!]Indexing page: 1

[%] Indexed 23 Images on Page 1.


[%] Downloading Image #1 from https://www.elanriverdistrict.com/app/uploads/2019/01/ian-dooley-281897-unsplash.jpg
[%] File Downloaded !

[%] Downloading Image #2 from https://c2.staticflickr.com/4/3357/4602700664_6d9473e26c_b.jpg
[%] File Downloaded !

[%] Downloading Image #3 from https://www.guinnessworldrecords.com/Images/Most-ice-cream-scoops-balanced-on-a-cone-header_tcm25-387618.jpg
[%] File Downloaded !

[%] Downloading Image #4 from https://64.media.tumblr.com/39c702e4cc530a5844c1ee25ca470ab4/c149e4939f250783-9c/s640x960/58a19e0b79126f5ee28cd700dfbee89eb3162727.jpg
[%] File Downloaded !

[%] Downloading Image #5 from https://www.packages.com.pk/wp-content/uploads/2017/10/cone-icecream-300x254.jpg
[%] File Downloaded !

[%] Downloading Image #6 from https://www.msjphotography.com/wp-content/uploads/2015/08/Ice-Cream-Cone-Skier-and-Snowboarder-Composite-GIF-Master.gif
[%] File Downloaded !

[%] Downloading Image #7 from 

# New section

In [10]:
import numpy as np

a = np.array([1,2])
a

array([1, 2])

In [11]:
import numpy as np

a=np.array([1,2,3,4,5])
a

array([1, 2, 3, 4, 5])

In [12]:
import numpy as np

a = np.array([1,2,3,4,5])
a.ndim


1

In [13]:
import numpy as np

a = np.array([[1,2,3,4,5],[4,5,6,7,8]])
a.ndim

2

In [14]:
# How do i convert Matrix to Vector? - flatten()
a.flatten()


array([1, 2, 3, 4, 5, 4, 5, 6, 7, 8])

In [15]:
#Preprocessing
# 1.resize
# 2.flatten


import os
import matplotlib.pyplot as plt
import numpy as np
from skimage.os import imread 
from skimage.transform import resize

target = []
images = []
flat_data = []

DATADIR = '/content/images'
CATEGORIES = ['pretty sunflower','rugby ball leather','ice cream cone']

for category in CATEGORIES:
  class_num = CATEGORIES.index(category) # Label encoding  the values
  path = os.path.join(DATADIR,category) # Create path to use all the images
  #/content/images/pretty sunflower
  for img in os.listdir(path):
   img_array = imread(os.path.join(path,img))
   #print(img_array.shape)
   #plt.imshow(img_array)
      img_resized = resize(img_array,(150,150,3)) # Normalizes the value from 0 to 1
      flat_data.append(img_resized.flatten())
      images.append(img_resized)
      target.append(class_num)

 flat_data = np.array(flat_data)     
target = np.array(target)
images = np.array(images)

IndentationError: ignored

In [ ]:
flat_data[0]

array([0.09607843, 0.09607843, 0.04901961, ..., 0.8627451 , 0.83137255,
       0.79803922])

In [ ]:
flat_data

[array([0.09607843, 0.09607843, 0.04901961, ..., 0.8627451 , 0.83137255,
        0.79803922]),
 array([0.09607843, 0.09607843, 0.04901961, ..., 0.8627451 , 0.83137255,
        0.79803922]),
 array([0.09607843, 0.09607843, 0.04901961, ..., 0.8627451 , 0.83137255,
        0.79803922]),
 array([0.09607843, 0.09607843, 0.04901961, ..., 0.8627451 , 0.83137255,
        0.79803922]),
 array([0.09607843, 0.09607843, 0.04901961, ..., 0.8627451 , 0.83137255,
        0.79803922]),
 array([0.09607843, 0.09607843, 0.04901961, ..., 0.8627451 , 0.83137255,
        0.79803922]),
 array([0.09607843, 0.09607843, 0.04901961, ..., 0.8627451 , 0.83137255,
        0.79803922]),
 array([0.09607843, 0.09607843, 0.04901961, ..., 0.8627451 , 0.83137255,
        0.79803922]),
 array([0.09607843, 0.09607843, 0.04901961, ..., 0.8627451 , 0.83137255,
        0.79803922]),
 array([0.09607843, 0.09607843, 0.04901961, ..., 0.8627451 , 0.83137255,
        0.79803922]),
 array([0.09607843, 0.09607843, 0.04901961, ..., 0

In [20]:
len(flat_data[0])

NameError: ignored

In [21]:
150*150

22500

In [22]:
150*150*3

67500

In [23]:
target

NameError: ignored

In [24]:
np.unique(target,return_counts=True)

NameError: ignored

In [25]:
unique,count = np.unique(target,return_counts=True)
plt.bar(CATEGORIES,count)

NameError: ignored

In [26]:
#Split data into Training and testing
from sklearn.model_selection import train_test_split
x_train,x_test,y_train,y_test = train_test_split(flat_data,target,
                                                 test_size=0.3,random_state=109)

NameError: ignored

In [27]:
from sklearn.model_selection import GridSearchCV
from sklearn import svm
param_grid = [
              {'C':[1,10,100,1000],'kernal':['linear']},
              {'C':[1,10,100,1000],'gamma':[0.001,0.0001],'kernal':['rbf']}
]

svc = svm.SVC(probability=True)
clf = GridSearchCV(svc,param_grid)
clf.fit(x_train,y_train)

NameError: ignored

In [28]:
y_pred = clf.predict(x_test)
y_pred

NameError: ignored

In [31]:
y_test

NameError: ignored

In [32]:
from sklearn.metrics import accuracy_score,confusion_matrix

In [33]:
accuracy_score(y_pred,y_test)

NameError: ignored

In [34]:
confusion_matrix(y_pred,y_test)

NameError: ignored

In [35]:
# Save the model using pickle library
import pickle
pickle.dumple(clf,open('img_model.p','wb'))

AttributeError: ignored

In [ ]:
model = pickle.load(open('img_model.p','rb'))

FileNotFoundError: ignored

In [ ]:


# Testing a brand new Image
flat_data = []
url = input('Enter your URL')
img = imread(url)
img_resized = resize(img,(150,150,3))
flat_data.append(img_resized.flatten())
flat_data = np.array(flat_data)
print(img.shape)
plt.imshow(img_resized)
y_out = modeel.predict(flat_data)
y_out = CATEGORIES[y_out[0]]
print(f'PREDICTED OUTPUT: {y_out}')

In [ ]:
!pip install streamlit

!pip install pyngrok
from pyngrok import ngrok

In [ ]:
!pip install sklearn_ train_ test_ split_downloader


In [ ]:
# Deployment :
# 1.WebPage - HTML/CSS/JS - Flask/Django
# 2.WebApp - Streamlit/Dash
# 3.Mobile APP - kotlin/java 

In [ ]:
%%writefile app.py
import streamlit as st
st.title('Image Classifier')

In [ ]:
!nohup streamlit run app.py &

url = ngrok.connect(port='8501')
url

In [ ]:
# AWS
# Azure
# GCP
# Heroku - Free Plaform for deploying